/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as EventsDraftRouteImport } from './routes/events/draft'
import { Route as EventsCreateRouteImport } from './routes/events/create'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdEditRouteImport } from './routes/events/$eventId/edit'
import { Route as EventsEventIdAnalyticsRouteImport } from './routes/events/$eventId/analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsDraftRoute = EventsDraftRouteImport.update({
  id: '/events/draft',
  path: '/events/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdEditRoute = EventsEventIdEditRouteImport.update({
  id: '/events/$eventId/edit',
  path: '/events/$eventId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdAnalyticsRoute = EventsEventIdAnalyticsRouteImport.update({
  id: '/events/$eventId/analytics',
  path: '/events/$eventId/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events/draft': typeof EventsDraftRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/me': typeof MeIndexRoute
  '/events/$eventId/analytics': typeof EventsEventIdAnalyticsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events/draft': typeof EventsDraftRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/me': typeof MeIndexRoute
  '/events/$eventId/analytics': typeof EventsEventIdAnalyticsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/create': typeof EventsCreateRoute
  '/events/draft': typeof EventsDraftRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/me/': typeof MeIndexRoute
  '/events/$eventId/analytics': typeof EventsEventIdAnalyticsRoute
  '/events/$eventId/edit': typeof EventsEventIdEditRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/create'
    | '/events/draft'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/me'
    | '/events/$eventId/analytics'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/create'
    | '/events/draft'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/me'
    | '/events/$eventId/analytics'
    | '/events/$eventId/edit'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/events/create'
    | '/events/draft'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/me/'
    | '/events/$eventId/analytics'
    | '/events/$eventId/edit'
    | '/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsCreateRoute: typeof EventsCreateRoute
  EventsDraftRoute: typeof EventsDraftRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  MeIndexRoute: typeof MeIndexRoute
  EventsEventIdAnalyticsRoute: typeof EventsEventIdAnalyticsRoute
  EventsEventIdEditRoute: typeof EventsEventIdEditRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/draft': {
      id: '/events/draft'
      path: '/events/draft'
      fullPath: '/events/draft'
      preLoaderRoute: typeof EventsDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/create': {
      id: '/events/create'
      path: '/events/create'
      fullPath: '/events/create'
      preLoaderRoute: typeof EventsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/edit': {
      id: '/events/$eventId/edit'
      path: '/events/$eventId/edit'
      fullPath: '/events/$eventId/edit'
      preLoaderRoute: typeof EventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/analytics': {
      id: '/events/$eventId/analytics'
      path: '/events/$eventId/analytics'
      fullPath: '/events/$eventId/analytics'
      preLoaderRoute: typeof EventsEventIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsCreateRoute: EventsCreateRoute,
  EventsDraftRoute: EventsDraftRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  MeIndexRoute: MeIndexRoute,
  EventsEventIdAnalyticsRoute: EventsEventIdAnalyticsRoute,
  EventsEventIdEditRoute: EventsEventIdEditRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
